### ISSUE TITLE
4.4.4 linking error on 15.1 beta2

### ISSUE THREAD

**Issue by c3ph3us** [n8fr8/orbot#20]
01-14 03:57:21.802 ? I/dalvikvm: Could not find method android.net.VpnService$Builder.addAllowedApplication, referenced from method org.torproject.android.vpn.OrbotVpnService.doLollipopAppRouting
01-14 03:57:21.802 ? I/dalvikvm: Could not find method android.net.VpnService$Builder.addDisallowedApplication, referenced from method org.torproject.android.vpn.OrbotVpnService.doLollipopAppRouting
01-14 03:57:21.802 ? W/dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lorg/torproject/android/vpn/OrbotVpnService;
01-14 03:57:21.812 ? E/AndroidRuntime: FATAL EXCEPTION: main
                                       Process: org.torproject.android, PID: 9964
                                       java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "sigemptyset" referenced by "libtun2socks.so"...
                                           at java.lang.Runtime.loadLibrary(Runtime.java:364)
                                           at java.lang.System.loadLibrary(System.java:526)
                                           at org.torproject.android.vpn.OrbotVpnService.<clinit>(OrbotVpnService.java:81)
                                           at org.torproject.android.service.TorService.onCreate(TorService.java:573)
                                           at android.app.ActivityThread.handleCreateService(ActivityThread.java:2620)
                                           at android.app.ActivityThread.access$1800(ActivityThread.java:144)
                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1328)
                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                           at android.os.Looper.loop(Looper.java:212)
                                           at android.app.ActivityThread.main(ActivityThread.java:5135)
                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
                                           at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
                                           at dalvik.system.NativeStart.main(Native Method)

**Comment by n8fr8** [comment]
Thanks for the report. Strange that the Lollipop only method was called on 4.x, but otherwise will see what the issue with the library build is. Could be an NDK version issue.

**Comment by c3ph3us** [comment]
Googles Android is going to be in the future as switch cheese :) all this mess gets from leaving sun api's  behind :D 

i don't have time to set ndk and all this dependencies to compile orbot - ill leave it for you :) till then i'll wait :v: 

have u ever consider to cooperate with cyanogenmod team to incorporated orbot into os as an security element?

**Comment by hardikhari96** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.torproject.android, PID: 26936
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libtun2socks.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at org.torproject.android.service.vpn.Tun2Socks.<clinit>(Tun2Socks.java:53)
        at org.torproject.android.service.vpn.Tun2Socks.init(Tun2Socks.java:57)
        at org.torproject.android.service.vpn.OrbotVpnManager.<init>(OrbotVpnManager.java:85)
        at org.torproject.android.service.OrbotService.onCreate(OrbotService.java:484)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4511)
        at android.app.ActivityThread.access$100(ActivityThread.java:306)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2176)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:263)
        at android.app.ActivityThread.main(ActivityThread.java:8276)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
I/Process: Sending signal. PID: 26936 SIG: 9
