### ISSUE TITLE
Missing asset file in X86 arch

### ISSUE THREAD

**Issue by Tornaco** [n8fr8/orbot#74]
Install on X86 emulator, we can see logs below:

```
07-10 05:13:04.487 11844 11890 D Orbot : checking binary version: null
07-10 05:13:04.488 11844 11890 D Orbot : upgrading binaries to latest version: 0.3.0.7-openssl1.0.2k-1
07-10 05:13:04.501 11844 11890 E Orbot : error onBind
07-10 05:13:04.501 11844 11890 E Orbot : java.io.FileNotFoundException: x86/obfs4proxy.mp3
07-10 05:13:04.501 11844 11890 E Orbot : at android.content.res.AssetManager.openAsset(Native Method)
07-10 05:13:04.501 11844 11890 E Orbot : at android.content.res.AssetManager.open(AssetManager.java:347)
07-10 05:13:04.501 11844 11890 E Orbot : at android.content.res.AssetManager.open(AssetManager.java:321)
07-10 05:13:04.501 11844 11890 E Orbot : at org.torproject.android.service.util.TorResourceInstaller.installResources(TorResourceInstaller.java:89)
07-10 05:13:04.501 11844 11890 E Orbot : at org.torproject.android.service.TorService.torUpgradeAndConfig(TorService.java:633)
07-10 05:13:04.501 11844 11890 E Orbot : at org.torproject.android.service.TorService.access$800(TorService.java:82)
07-10 05:13:04.501 11844 11890 E Orbot : at org.torproject.android.service.TorService$2.run(TorService.java:589)
07-10 05:13:04.501 11844 11890 E Orbot : at java.lang.Thread.run(Thread.java:761)
07-10 05:13:04.501 11844 11890 D Orbot : error finding exiting process: java.io.FileNotFoundException: x86/obfs4proxy.mp3
07-10 05:13:05.374 11844 11844 D Orbot : handleIntents android.intent.action.MAIN
```

So, there are errors when files missing for x86 arch. Pls fix.

**Comment by Tornaco** [comment]
How to reproduce:
1. Launch app.
2. Click Start button.

**Comment by anupsv** [comment]
Same error here as well, when using with android studio emulator.

**Comment by goapunk** [comment]
AFAIK the external dependencies (Tor, OpenSSL, Pluto, etc..) are only compiled for arm by default. If you want to run Orbot in the emulator you'd either have to build them for x86 (e.g. modify the Makefile) or use the slower arm image.

**Comment by n8fr8** [comment]
There is a new beta release build to try:
https://github.com/n8fr8/orbot/releases/tag/16.0.2-BETA-3

the "armeabi-v7a" APK should work for most people, or just get the "universal" one if you aren't sure.

**Comment by n8fr8** [comment]
Of course for x86 devices, you should grab that APK!
